In [11]:
import torch.nn as nn
import torch.nn.functional as F
import torch

In [7]:
class MultilayerPerceptron(nn.Module):
    
    def __init__(self, input_dim, hidden_dim, output_dim):
        
        super(MultilayerPerceptron, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, x_in, apply_softmax=False):
        
        intermediate = F.relu(self.fc1(x_in))
        output = self.fc2(intermediate)
        
        if apply_softmax:
            output = F.softmax(output, dim=1)
        
        return output
        
        

In [8]:
batch_size=2
input_dim=3
hidden_dim=100
output_dim=4

mlp = MultilayerPerceptron(input_dim, hidden_dim, output_dim)

In [9]:
print(mlp)

MultilayerPerceptron(
  (fc1): Linear(in_features=3, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=4, bias=True)
)


In [10]:
def describe(x):
    print('Type: {}'.format(x.type()))
    print('Shape/size: {}'.format(x.shape))
    print('values: \n{}'.format(x))

In [12]:
x_input = torch.rand(batch_size, input_dim)
describe(x_input)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
values: 
tensor([[0.1875, 0.1965, 0.6337],
        [0.0040, 0.7937, 0.1010]])


In [19]:
y_output = mlp(x_input, apply_softmax=True)
describe(y_output)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4])
values: 
tensor([[0.2198, 0.2932, 0.2294, 0.2576],
        [0.1975, 0.3502, 0.2060, 0.2464]], grad_fn=<SoftmaxBackward>)


In [20]:
import numpy as np

In [21]:
np.dot([-3,-8,7,-4],[3,-7,5,3])

70

In [22]:
class Perceptron(nn.Module):
    
    def __init__(self, input_dim):
        super(Perceptron, self).__init__()
        self.fc1 = nn.Linear(input_dim, 1)
        
    def forward(self, x_in):
        return torch.sigmoid(self.fc1(x_in)).squeeze()

In [23]:
import matplotlib.pyplot as plt

In [27]:
x = torch.range(-5.,5.,0.1)
y = torch.nn.ReLU(x)
plt.plot(x.numpy(), y.numpy())
plt.show()

/home/achint/Raghava/pm4py_sources/venv/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


ModuleAttributeError: 'ReLU' object has no attribute 'numpy'

In [29]:
import torch.nn as nn
import torch

In [30]:
softmax = nn.Softmax(dim=1)
x_input = torch.randn(1, 3)
y_output = softmax(x_input)

print(x_input)
print(y_output)

tensor([[-0.7485,  0.4533,  1.3088]])
tensor([[0.0823, 0.2737, 0.6440]])


In [31]:
print(torch.sum(y_output, dim=1))

tensor([1.0000])


In [32]:
mse_loss = nn.MSELoss()
outputs = torch.randn(3, 5, requires_grad=True)
targets = torch.randn(3, 5)


In [33]:
outputs, targets

(tensor([[-2.0179, -1.0739, -2.9279, -1.1493, -0.8921],
         [-1.0750, -0.4127,  1.2886,  0.2775, -1.1833],
         [ 1.1413, -1.5007,  1.2514, -1.1650,  0.4940]], requires_grad=True),
 tensor([[ 0.2382,  1.2078,  0.0554, -0.0967,  0.3165],
         [-1.4838,  0.2455,  0.7597, -0.1565,  2.0114],
         [-0.1892, -1.1038, -1.0963,  0.6421,  2.0161]]))

In [34]:
loss = mse_loss(outputs, targets)
print(loss)

tensor(3.0707, grad_fn=<MseLossBackward>)


In [35]:
ce_loss = nn.CrossEntropyLoss()
outputs = torch.randn(3, 5, requires_grad=True)
targets = torch.tensor([1, 0, 3], dtype=torch.int64)
loss = ce_loss(outputs, targets)
print(loss)

tensor(1.4003, grad_fn=<NllLossBackward>)


In [36]:
outputs, targets

(tensor([[ 8.9319e-01, -5.5658e-01, -2.7968e-01, -1.1566e-01,  1.5228e-01],
         [ 1.0543e+00, -1.1951e+00, -2.1246e+00, -1.2501e+00, -6.0949e-01],
         [ 9.2083e-01,  5.7982e-03, -1.3690e-01,  4.1134e-01, -1.1035e-03]],
        requires_grad=True),
 tensor([1, 0, 3]))

In [38]:
bce_loss = nn.BCELoss()
sigmoid = nn.Sigmoid()
probabilities = sigmoid(torch.randn(4, 1, requires_grad=True))
targets = torch.tensor([1, 0, 1, 0], dtype=torch.float32).view(4, 1)
loss = bce_loss(probabilities, targets)
print(probabilities)
print(loss)

tensor([[0.6804],
        [0.6254],
        [0.7319],
        [0.7631]], grad_fn=<SigmoidBackward>)
tensor(0.7798, grad_fn=<BinaryCrossEntropyBackward>)


In [39]:
import torch.optim as optim

In [40]:
input_dim = 2
lr = 0.001


In [41]:
perceptron = Perceptron(input_dim=input_dim)
bce_loss = nn.BCELoss()
optimizer = optim.Adam(params=perceptron.parameters(), lr=lr)